services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bisnis-hp-app
    restart: unless-stopped
    ports:
      - "8093:80"
    volumes:
      # INI WAJIB ADA AGAR SINKRON:
      - ./:/var/www
    environment:
      TZ: "Asia/Jakarta"
      APP_NAME: "${APP_NAME}"
      APP_ENV: "${APP_ENV}"
      APP_KEY: "${APP_KEY}"
      APP_DEBUG: "${APP_DEBUG}"
      APP_URL: "${APP_URL}"
      ASSET_URL: "${ASSET_URL}"
      DB_CONNECTION: mysql
      DB_HOST: mysql_db
      DB_PORT: 3306
      DB_DATABASE: "${DB_DATABASE}"
      DB_USERNAME: "${DB_USERNAME}"
      DB_PASSWORD: "${DB_PASSWORD}"
    networks:
      - db_master_shared

networks:
  db_master_shared:
    external: true
